import * as React from "react"
import { api, type QuizQuestion, type Flashcard } from "@/lib/api"
import { useLanguage } from "@/context/LanguageContext"
import { useToast } from "@/context/ToastContext"
import { Button } from "@/components/ui/button"
import { LoadingState } from "@/components/Spinner"
import { Icon } from "@/components/ui/icon"
import { downloadFile } from "@/lib/export"

interface AgentPanelProps {
  files: string[]
}

interface PlanStep {
  action: "summary" | "notes" | "quiz" | "flashcards" | "research"
  label: string
  source?: string
  topic?: string
  num_questions?: number
  num_cards?: number
}

interface StepResult extends PlanStep {
  status: "pending" | "running" | "done" | "error"
  error?: string
  textResult?: string
  quizResult?: QuizQuestion[]
  flashcardResult?: Flashcard[]
}

export function AgentPanel({ files }: AgentPanelProps) {
  const { t } = useLanguage()
  const { toast } = useToast()
  const [goal, setGoal] = React.useState("")
  const [planning, setPlanning] = React.useState(false)
  const [running, setRunning] = React.useState(false)
  const [steps, setSteps] = React.useState<StepResult[]>([])

  async function handlePlanAndRun() {
    if (!goal.trim()) return
    setPlanning(true)
    setSteps([])
    let plan: PlanStep[] = []
    try {
      const { data } = await api.post("/generate/agent-plan", { goal })
      plan = data.steps || []
    } catch (err: any) {
      toast(err?.response?.data?.detail || t("agentPanel.errPlanFailed"), "error")
      setPlanning(false)
      return
    }
    if (plan.length === 0) {
      toast(t("agentPanel.errNoPlan"), "error")
      setPlanning(false)
      return
    }
    setSteps(plan.map((s) => ({ ...s, status: "pending" })))
    setPlanning(false)
    setRunning(true)
    for (let i = 0; i < plan.length; i++) {
      const step = plan[i]
      setSteps((prev) => prev.map((s, idx) => (idx === i ? { ...s, status: "running" } : s)))
      try {
        if (step.action === "summary") {
          const { data } = await api.post("/generate/summary", { source: step.source })
          setSteps((prev) => prev.map((s, idx) => (idx === i ? { ...s, status: "done", textResult: data.result } : s)))
        } else if (step.action === "notes") {
          const { data } = await api.post("/generate/notes", { source: step.source })
          setSteps((prev) => prev.map((s, idx) => (idx === i ? { ...s, status: "done", textResult: data.result } : s)))
        } else if (step.action === "quiz") {
          const { data } = await api.post(
            "/generate/quiz",
            { source: step.source },
            { params: { num_questions: step.num_questions || 5 } }
          )
          setSteps((prev) => prev.map((s, idx) => (idx === i ? { ...s, status: "done", quizResult: data.result } : s)))
        } else if (step.action === "flashcards") {
          const { data } = await api.post(
            "/generate/flashcards",
            { source: step.source },
            { params: { num_cards: step.num_cards || 10 } }
          )
          setSteps((prev) => prev.map((s, idx) => (idx === i ? { ...s, status: "done", flashcardResult: data.result } : s)))
        } else if (step.action === "research") {
          const { data } = await api.post("/generate/research", { topic: step.topic })
          setSteps((prev) => prev.map((s, idx) => (idx === i ? { ...s, status: "done", textResult: data.report } : s)))
        }
      } catch (err: any) {
        const message = err?.response?.data?.detail || t("agentPanel.errStepFailed")
        setSteps((prev) => prev.map((s, idx) => (idx === i ? { ...s, status: "error", error: message } : s)))
      }
    }
    setRunning(false)
  }

  function handleDownloadAll() {
    const done = steps.filter((s) => s.status === "done")
    if (done.length === 0) return
    const sections = done.map((s) => {
      let body = ""
      if (s.textResult) {
        body = s.textResult
      } else if (s.quizResult) {
        body = s.quizResult
          .map(
            (q, i) =>
              `**Q${i + 1}. ${q.question}**\n` +
              Object.entries(q.options)
                .map(([k, v]) => `- ${k}. ${v}${k === q.correct ? " ✅" : ""}`)
                .join("\n") +
              `\n\n> ${q.explanation || ""}`
          )
          .join("\n\n")
      } else if (s.flashcardResult) {
        body = s.flashcardResult.map((c, i) => `**${i + 1}. ${c.front}**\n${c.back}`).join("\n\n")
      }
      return `## ${s.label}\n\n${body}`
    })
    const content = `# Agent Report\n\n**Goal:** ${goal}\n**Generated:** ${new Date().toLocaleString()}\n\n---\n\n${sections.join(
      "\n\n---\n\n"
    )}\n\n---\n*Generated by Documind AI Agent*\n`
    downloadFile("agent_report.md", content, "text/markdown")
  }

  if (files.length === 0) {
    return <p className="text-sm text-text-muted">{t("common.uploadFirst")}</p>
  }

  const doneCount = steps.filter((s) => s.status === "done").length

  return (
    <div className="flex flex-col gap-4">
      <h2 className="text-lg font-semibold text-text">{t("agentPanel.title")}</h2>
      <p className="text-xs text-text-muted">{t("agentPanel.description")}</p>

      <div className="flex flex-col gap-2 sm:flex-row">
        <textarea
          value={goal}
          onChange={(e) => setGoal(e.target.value)}
          placeholder={t("agentPanel.placeholder")}
          rows={2}
          disabled={planning || running}
          className="flex-1 resize-none rounded-lg border border-border bg-surface px-3 py-2 text-sm text-text disabled:opacity-50"
        />
        <Button onClick={handlePlanAndRun} disabled={planning || running || !goal.trim()} className="shrink-0">
          {planning || running ? (
            planning ? t("agentPanel.planning") : t("agentPanel.running")
          ) : (
            <>
              <Icon name="smart_toy" size={17} />
              {t("agentPanel.run")}
            </>
          )}
        </Button>
      </div>

      {steps.length > 0 && (
        <div className="flex flex-col gap-3">
          {steps.map((s, i) => (
            <div key={i} className="rounded-2xl border border-white/10 bg-white/3 p-4">
              <div className="mb-2 flex items-center justify-between gap-2">
                <span className="text-sm font-medium text-text">
                  {i + 1}. {s.label}
                </span>
                {s.status === "pending" && <span className="text-xs text-text-muted">{t("agentPanel.queued")}</span>}
                {s.status === "running" && <span className="text-xs text-text-muted">{t("agentPanel.running")}</span>}
                {s.status === "error" && <span className="text-xs text-danger">{s.error}</span>}
                {s.status === "done" && <span className="text-xs text-success">{t("agentPanel.done")}</span>}
              </div>
              {s.status === "running" && <LoadingState label="" />}
              {s.status === "done" && s.textResult && (
                <div className="whitespace-pre-wrap text-sm leading-relaxed text-text-muted">{s.textResult}</div>
              )}
              {s.status === "done" && s.quizResult && (
                <p className="text-sm text-text-muted">
                  {s.quizResult.length} {t("agentPanel.quizGenerated")}
                </p>
              )}
              {s.status === "done" && s.flashcardResult && (
                <p className="text-sm text-text-muted">
                  {s.flashcardResult.length} {t("agentPanel.flashcardsGenerated")}
                </p>
              )}
            </div>
          ))}
        </div>
      )}

      {doneCount > 0 && !running && (
        <div>
          <Button variant="outline" onClick={handleDownloadAll}>
            ⬇ {t("agentPanel.downloadReport")} ({doneCount})
          </Button>
        </div>
      )}
    </div>
  )
}
