import { useNavigate } from "react-router-dom"

export default function TermsOfServicePage() {
  const navigate = useNavigate()

  return (
    <div className="min-h-screen bg-black px-6 py-16 text-white">
      <div className="mx-auto max-w-3xl">
        <button onClick={() => navigate("/")} className="mb-8 text-sm font-semibold text-emerald-400 hover:underline">
          ← Back to Documind AI
        </button>

        <h1 className="text-3xl font-extrabold tracking-tight sm:text-4xl">Terms of Service</h1>
        <p className="mt-2 text-sm text-white/40">Last updated: {new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}</p>

        <div className="mt-10 flex flex-col gap-8 text-sm leading-relaxed text-white/70">
          <section>
            <h2 className="mb-2 text-lg font-bold text-white">1. Acceptance of terms</h2>
            <p>By creating an account or using Documind AI, you agree to these Terms of Service and our Privacy Policy.</p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-bold text-white">2. The service</h2>
            <p>
              Documind AI lets you upload PDFs and use AI-powered tools — chat, summaries, quizzes, flashcards,
              comparisons, research, and a document editor (text editing, e-signatures, form filling, OCR, and
              redaction) — to work with them. AI features require your own Google Gemini API key.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-bold text-white">3. Your account</h2>
            <p>
              You're responsible for keeping your login credentials secure and for all activity under your account.
              You must provide accurate information when signing up.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-bold text-white">4. Subscriptions &amp; billing</h2>
            <p>
              The Pro plan is billed monthly through Stripe. You can cancel anytime from the Billing Portal in your
              account sidebar — your Pro access continues until the end of the current billing period. We don't
              store your payment details; Stripe handles all billing directly.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-bold text-white">5. Acceptable use</h2>
            <ul className="list-disc space-y-1.5 pl-5">
              <li>Only upload documents you have the legal right to use.</li>
              <li>Don't use the service for anything illegal, harmful, or abusive.</li>
              <li>Don't attempt to circumvent rate limits, plan restrictions, or security controls.</li>
              <li>Don't use the service to generate or process content that violates others' rights.</li>
            </ul>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-bold text-white">6. AI-generated content</h2>
            <p>
              Responses, summaries, quizzes, and edits are generated by AI and may contain mistakes. Always verify
              anything important — especially for legal, financial, or medical documents — before relying on it.
              Documind AI is not a substitute for professional advice.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-bold text-white">7. Your content</h2>
            <p>
              You retain full ownership of any documents you upload. We don't claim any rights to your content, and
              we don't use it to train AI models. Uploaded documents are held in memory only for your session and
              are not permanently stored.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-bold text-white">8. Termination</h2>
            <p>
              You may delete your account at any time from Account Settings. We may suspend or terminate accounts
              that violate these terms, including abusive or illegal use of the service.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-bold text-white">9. Limitation of liability</h2>
            <p>
              Documind AI is provided "as is," without warranties of any kind. We're not liable for any indirect,
              incidental, or consequential damages arising from your use of the service, including inaccuracies in
              AI-generated content.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-bold text-white">10. Changes to these terms</h2>
            <p>
              We may update these terms as the product evolves. Continued use of the service after changes means
              you accept the updated terms.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-bold text-white">11. Contact</h2>
            <p>
              Questions about these terms? Reach us at{" "}
              <a href="mailto:support@documindai.online" className="text-emerald-400 hover:underline">
                support@documindai.online
              </a>.
            </p>
          </section>
        </div>
      </div>
    </div>
  )
}
