import type { QuizQuestion, Flashcard } from "@/lib/api"

export function downloadFile(filename: string, content: string | Blob, mime = "text/plain") {
  const blob = content instanceof Blob ? content : new Blob([content], { type: mime })
  const url = URL.createObjectURL(blob)
  const a = document.createElement("a")
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  a.remove()
  URL.revokeObjectURL(url)
}

export function stripMarkdown(text: string): string {
  return text
    .replace(/\*\*(.*?)\*\*/g, "$1")
    .replace(/(?<!\*)\*(?!\*)(.*?)(?<!\*)\*(?!\*)/g, "$1")
    .replace(/^#{1,6}\s*/gm, "")
    .replace(/^>\s?/gm, "")
    .trim()
}

export function buildExportMarkdown(title: string, meta: Record<string, string>, body: string): string {
  const metaLines = Object.entries(meta)
    .map(([k, v]) => `**${k}:** ${v}`)
    .join("\n")
  const generated = new Date().toLocaleString()
  return (
    `# ${title}\n\n` +
    `${metaLines}\n` +
    `**Generated:** ${generated}\n\n` +
    `---\n\n` +
    `${body}\n\n` +
    `---\n` +
    `*Generated by Documind AI*\n`
  )
}

export function buildQuizMarkdown(source: string, quiz: QuizQuestion[]): string {
  const lines: string[] = [
    `# Quiz — ${source}`,
    "",
    `**Generated:** ${new Date().toLocaleString()}`,
    `**Total Questions:** ${quiz.length}`,
    "",
    "---",
    "",
  ]
  quiz.forEach((q, i) => {
    lines.push(`### Q${i + 1}. ${q.question}`, "")
    Object.entries(q.options).forEach(([k, v]) => {
      const marker = k === q.correct ? " ✅" : ""
      lines.push(`- **${k}.** ${v}${marker}`)
    })
    lines.push("", `**Correct Answer:** ${q.correct}`, "", `> ${q.explanation || ""}`, "", "---", "")
  })
  lines.push("*Generated by Documind AI*")
  return lines.join("\n")
}

export function buildFlashcardsCsv(cards: Flashcard[]): string {
  const escape = (val: string) => `"${val.replace(/"/g, '""')}"`
  const header = "#,Question,Answer"
  const rows = cards.map((c, i) => `${i + 1},${escape(stripMarkdown(c.front))},${escape(stripMarkdown(c.back))}`)
  return "﻿" + [header, ...rows].join("\n")
}
